ACCESS_TOKEN = "YOUR TWITTER ACCESS TOKEN"

ACCESS_TOKEN_SECRET = "YOUR TWITTER SECRET ACCESS TOKEN"

CONSUMER_KEY = "YOUR TWITTER CONSUMER KEY"

CONSUMER_SECRET = "YOUR TWITTER SECRET CONSUMER KEY"
